use sakila;
-- 1. List the number of films per category.
select c.name as category_name, COUNT(f.film_id) as number_of_films
from film f
join film_category fc on f.film_id = fc.film_id
join category c on fc.category_id = c.category_id
group by c.name;

-- 2. Retrieve the store ID, city, and country for each store.
select s.store_id, c.city, co.country from store s
join address a on s.address_id = a.address_id
join city c on a.city_id = c.city_id
join country co on c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
select s.store_id, sum(p.amount) as total_revenue
from store s
join staff st on s.store_id = st.store_id
join rental r on st.staff_id = r.staff_id
join payment p on r.rental_id = p.rental_id
group by s.store_id;

-- 4. Determine the average running time of films for each category.
select c.name as category_name, avg(f.length) as avg_running_time
from film f
join film_category fc on f.film_id = fc.film_id
join category c on fc.category_id = c.category_id
group by c.name;